// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sm.Repository.EfSqlserver;

#nullable disable

namespace Sm.Repository.EfSqlserver.Migrations
{
    [DbContext(typeof(SmDbContext))]
    [Migration("20250507143801_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sm.Share.Entities.ExecutableActionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sm_ExecutableAction", (string)null);
                });

            modelBuilder.Entity("Sm.Share.Entities.StateMachineEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InitialState")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sm_StateMachine", (string)null);
                });

            modelBuilder.Entity("Sm.Share.Entities.StateSettingsActionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationType")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutableActionId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StateSettingsId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StateSettingsId");

                    b.ToTable("Sm_StateSettingsAction", (string)null);
                });

            modelBuilder.Entity("Sm.Share.Entities.StateSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StateMachineId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StateMachineId");

                    b.ToTable("Sm_StateSettings", (string)null);
                });

            modelBuilder.Entity("Sm.Share.Entities.TransitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtState")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StateSettingsId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StateSettingsId");

                    b.ToTable("Sm_Transition", (string)null);
                });

            modelBuilder.Entity("Sm.Share.Entities.StateSettingsActionEntity", b =>
                {
                    b.HasOne("Sm.Share.Entities.StateSettingsEntity", "StateSettings")
                        .WithMany("Actions")
                        .HasForeignKey("StateSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateSettings");
                });

            modelBuilder.Entity("Sm.Share.Entities.StateSettingsEntity", b =>
                {
                    b.HasOne("Sm.Share.Entities.StateMachineEntity", "StateMachine")
                        .WithMany("StateSettings")
                        .HasForeignKey("StateMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateMachine");
                });

            modelBuilder.Entity("Sm.Share.Entities.TransitionEntity", b =>
                {
                    b.HasOne("Sm.Share.Entities.StateSettingsEntity", "StateSettings")
                        .WithMany("Transitions")
                        .HasForeignKey("StateSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateSettings");
                });

            modelBuilder.Entity("Sm.Share.Entities.StateMachineEntity", b =>
                {
                    b.Navigation("StateSettings");
                });

            modelBuilder.Entity("Sm.Share.Entities.StateSettingsEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
